config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cooking_repertoires, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :cooking_repertoire_tags, only: [:create]
  resources :tags, only: [:index]
  resources :menus, only: [:index, :new, :create]
  root to: 'menus#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cooking_repertoire.rb
class CookingRepertoire < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: { maximum: 50 }

  validate :tag_size_limit

  has_many :cooking_repertoire_tags
  has_many :tags, through: :cooking_repertoire_tags
  accepts_nested_attributes_for :cooking_repertoire_tags
  has_many :menus

  scope :deleted, -> { joins(:tags).where(tags: { name: Tag.human_attribute_name(:delete) }) }
  scope :valid, -> { where.not(id: CookingRepertoire.deleted) }
  scope :random, -> { CookingRepertoire.valid.sample }

  private

  def tag_size_limit
    if cooking_repertoire_tags.empty?
      errors.add(:base, I18n.t('activerecord.errors.messages.no_select'))
    elsif cooking_repertoire_tags.size > 3
      errors.add(:base, I18n.t('activerecord.errors.messages.more_than_3'))
    end
  end
end

app/models/cooking_repertoire_tag.rb
class CookingRepertoireTag < ApplicationRecord
  belongs_to :cooking_repertoire
  belongs_to :tag
end

app/models/menu.rb
class Menu < ApplicationRecord
  validates :date, presence: true, uniqueness: true

  belongs_to :cooking_repertoire

  def self.make(from, to, not_duplicate_day, candidate_repertoires)
    ActiveRecord::Base.transaction do
      (from..to).each { |day| make_for_one_day(not_duplicate_day, day, candidate_repertoires) }
    end
  rescue StandardError => e
    puts e.message
  end

  class << self
    private

    def make_for_one_day(not_duplicate_day, day, candidate_repertoires)
      tags = exclude_tags(not_duplicate_day, day)
      exclude_repertoire = CookingRepertoire.joins(:tags).where(tags: { id: tags })
      cooking_repertoire_id = candidate_repertoires.where.not(id: exclude_repertoire).sample.id
      menu = Menu.find_or_initialize_by(date: day)
      menu.update_attributes!({ cooking_repertoire_id: cooking_repertoire_id })
    end

    def exclude_tags(not_duplicate_day, day)
      tags = []
      (1..not_duplicate_day).each do |i|
        before_day = day - i
        before_menu = Menu.find_by(date: before_day)
        next if before_menu.nil?

        cooking_repertoire_id = before_menu.cooking_repertoire_id
        tag = CookingRepertoire.find(cooking_repertoire_id).tags
        tags += tag
      end
      tags
    end
  end
end

app/models/menu_candidate_tag.rb
class MenuCandidateTag < ApplicationRecord
  belongs_to :tag

  def self.make(tag_candidates)
    MenuCandidateTag.where.not(tag_id: tag_candidates).destroy_all
    tag_candidates.each do |menu_candidate_tag|
      tag_id = menu_candidate_tag.to_i
      MenuCandidateTag.create(tag_id: tag_id) unless MenuCandidateTag.where(tag_id: tag_id).exists?
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :cooking_repertoire_tags
  has_many :cooking_repertoires, through: :cooking_repertoire_tags
  has_one :menu_candidate_tag

  scope :category, -> { where.not(name: I18n.t('activerecord.attributes.tag.delete')) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cooking_repertoire_tags_controller.rb
class CookingRepertoireTagsController < ApplicationController
  def create
    cooking_repertoire_and_tag
    cooking_repertoire_tag = CookingRepertoireTag.new(cooking_repertoire_id: @cooking_repertoire.id, tag_id: @tag.id)
    if cooking_repertoire_tag.save
      redirect_to tags_path, notice: t('.deleted_repertoire', { name: @cooking_repertoire.name })
    else
      redirect_to cooking_repertoire_path(@cooking_repertoire), notice: t('.failed_delete')
    end
  end

  private

  def cooking_repertoire_and_tag
    @cooking_repertoire = CookingRepertoire.find(params[:format])
    @tag = Tag.find_by(name: Tag.human_attribute_name(:delete))
  end
end

app/controllers/cooking_repertoires_controller.rb
class CookingRepertoiresController < ApplicationController
  before_action :find_repertoire, only: [:show, :edit, :update, :destroy]

  def index
    redirect_to new_cooking_repertoire_path
  end

  def new
    @cooking_repertoire = CookingRepertoire.new
    @tags = Tag.category
  end

  def create
    @cooking_repertoire = CookingRepertoire.new(cooking_repertoire_params)
    @tags = Tag.category

    if @cooking_repertoire.save
      redirect_to tags_path, notice: t('.added_repertoire', { name: @cooking_repertoire.name })
    else
      render :new
    end
  end

  def edit
    @tags = Tag.category
  end

  def update
    @tags = Tag.category

    if @cooking_repertoire.update(cooking_repertoire_params)
      redirect_to tags_path, notice: t('.edited_repertoire', { name: @cooking_repertoire.name })
    else
      render :edit
    end
  end

  def destroy
    redirect_to :tags, notice: t('.deleted_repertoire', { name: @cooking_repertoire.name })
  end

  private

  def cooking_repertoire_params
    params.require(:cooking_repertoire).permit(:name, { tag_ids: [] })
  end

  def find_repertoire
    @cooking_repertoire = CookingRepertoire.find(params[:id])
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :initialize_menu_params, only: [:create]
  before_action :save_menu_candidate_tags, only: [:create]

  def index
    @menus = Menu.where('date >= ?', Date.today).order(:date)
  end

  def new
    unless CookingRepertoire.valid.exists?
      redirect_to new_cooking_repertoire_path, notice: t('.add_cooking_repertoire')
    end
    @menu = Menu.new
    @tags = Tag.category
  end

  def create
    repertoire_candidates
    if Menu.make(@from_date, @to_date, @not_duplicate_day, @repertoire_candidates)
      redirect_to menus_path, notice: added_message(@from_date, @to_date)
    else
      redirect_to new_menu_path, notice: t('.creation_failed')
    end
  end

  private

  def initialize_menu_params
    @period = params[:menu][:period].to_i
    @date = params[:menu][:date]
    check_if_the_date_is_valid
    @not_duplicate_day = params[:menu][:not_duplicate_day].to_i
  end

  def check_if_the_date_is_valid
    if @date.blank?
      redirect_to new_menu_path, notice: t('.creation_failedon_start_date')
    else
      @from_date = Date.parse(@date)
      @to_date = @from_date + @period - 1
    end
  end

  def save_menu_candidate_tags
    @tag_candidates = params[:tag_candidates]
    if @tag_candidates.nil?
      redirect_to new_menu_path, notice: t('.tag_candidate_nil')
    else
      MenuCandidateTag.make(@tag_candidates[:tags])
    end
  end

  def added_message(from_date, to_date)
    if from_date == to_date
      t('.added_menu', { day: l(from_date) })
    else
      t('.added_menus', { start_day: l(from_date), end_day: l(to_date) })
    end
  end

  def repertoire_candidates
    candidate_tags = Tag.joins(:menu_candidate_tag)
    exclude_tags = Tag.where.not(id: candidate_tags)
    exclude_repertoires = CookingRepertoire.joins(:tags).where(tags: { id: exclude_tags })
    @repertoire_candidates = CookingRepertoire.where.not(id: exclude_repertoires)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.category
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
  def periods
    { I18n.t('.menus.new.one_day') => 1, I18n.t('.menus.new.seven_days') => 7, I18n.t('.menus.new.thirty_days') => 30 }
  end

  def not_duplicate_days
    not_duplicate_days = {}
    tags = []
    (1..7).each do |i|
      tags += before_tags(i)
      exclude_repertoire = CookingRepertoire.joins(:tags).where(tags: { id: tags })
      cooking_repertoire = CookingRepertoire.valid.where.not(id: exclude_repertoire)
      make_not_duplicate_days(cooking_repertoire, not_duplicate_days, i)
    end
    not_duplicate_days
  end

  def before_tags(num)
    before_day = Date.today - num
    before_menu = Menu.find_by(date: before_day)
    return [] if before_menu.nil?

    cooking_repertoire_id = before_menu.cooking_repertoire_id
    CookingRepertoire.find(cooking_repertoire_id).tags
  end

  def make_not_duplicate_days(cooking_repertoire, not_duplicate_days, num)
    if cooking_repertoire.empty? && num == 1
      not_duplicate_days[I18n.t('.menus.new.day', one_day: 0)] = 0
    elsif cooking_repertoire.empty?
    else
      not_duplicate_days[I18n.t('.menus.new.day', one_day: num)] = num
    end
  end
end

app/views/cooking_repertoires/_form.slim
= form_with model: cooking_repertoire, local: true do |form|
  - if cooking_repertoire.errors.any?
    - cooking_repertoire.errors.full_messages.each do |message|
      .alert.alert-danger = message
  .form-group
    .required = form.label :name
    = form.text_field :name, class: 'form-control input-lg'
  .form-group
    .required.my-2 = t('.supplement_info')
    = form.collection_check_boxes :tag_ids, tags, :id, :name do |b|
      = b.label(class: 'form-control mb-3 font-size-lg') do
        = b.check_box class: 'mr-2'
        = b.object.name
  .form-group
    = form.submit class: 'btn btn-lg btn-warning text-light form-control mb-3'

app/views/cooking_repertoires/edit.slim
h4.py-3.bg-warning.text-light.text-center.fixed-top
  = t('.title')
  .d-flex.justify-content-between
    = link_to t('.back'), cooking_repertoire_path(@cooking_repertoire), class: 'small position-absolute link'
.container.mt-3
  = render 'form', cooking_repertoire: @cooking_repertoire, tags: @tags

app/views/cooking_repertoires/new.slim
h4.py-3.text-center.bg-primary.text-light.fixed-top = t('.title')
.container.pt-3
  - if flash.notice.present?
    .alert.alert-danger = flash.notice
.container.mt-3
  = render 'form', cooking_repertoire: @cooking_repertoire, tags: @tags

app/views/cooking_repertoires/show.slim
h4.py-3.bg-warning.text-light.text-center.fixed-top
  = t('.title')
  .d-flex.justify-content-between
    = link_to t('.back'), tags_path, class: 'small position-absolute link'
    = link_to t('.edit'), edit_cooking_repertoire_path, class: 'small position-absolute link right-link'
.table-responsive
  table.table.text-nowrap.mt-5.border-bottom
    tbody
      tr
        th = CookingRepertoire.human_attribute_name(:name)
        td = @cooking_repertoire.name
      tr
        th = CookingRepertoire.human_attribute_name(:tag)
        td
          - @cooking_repertoire.cooking_repertoire_tags.each.with_index(1) do |cooking_repertoire_tag, index|
            - if index == @cooking_repertoire.cooking_repertoire_tags.size
              = cooking_repertoire_tag.tag.name
            - else
              = "#{cooking_repertoire_tag.tag.name}, "
      tr
        th = CookingRepertoire.human_attribute_name(:created_at)
        td = @cooking_repertoire.created_at.to_s(:datetime_jp)
      tr
        th = CookingRepertoire.human_attribute_name(:updated_at)
        td = @cooking_repertoire.updated_at.to_s(:datetime_jp)
.container.text-center
  = link_to t('.delete'), cooking_repertoire_tags_path(@cooking_repertoire), method: :post, data: { confirm: t('.delete_confirmation', {name: @cooking_repertoire.name}) }, class: 'btn btn-danger center-block'

app/views/layouts/_footer.slim
ul.nav.nav-justified.nav-tabs.fixed-bottom.bg-light
  li class="nav-item border-right text-secondary #{'active text-warning' if current_page?(menus_path)}"
    i.fas.fa-calendar-minus
    = link_to t('.menus'), menus_path, class: 'nav-link text-secondary stretched-link btn-ignore'
  li class="nav-item border-right text-secondary #{'active text-warning' if current_page?(new_menu_path)}"
    i.fas.fa-calendar-minus
    i.fas.fa-pen
    = link_to t('.make_menu'), new_menu_path, class: 'nav-link text-secondary stretched-link'
  li class="nav-item border-right text-secondary #{'active text-warning' if current_page?(tags_path)}"
    i.fas.fa-book-open
    = link_to t('.repertoires'), tags_path, class: 'nav-link text-secondary stretched-link'
  li class="nav-item text-secondary #{'active text-warning' if current_page?(new_cooking_repertoire_path) || (request.path == '/cooking_repertoires')}"
    i.fas.fa-book-open
    i.fas.fa-plus
    = link_to t('.add_repertoire'), new_cooking_repertoire_path, class: 'nav-link text-secondary stretched-link'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | TodaysDinner
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield
    = render 'layouts/footer'

app/views/menus/index.slim
h4.py-3.text-center.bg-warning.text-light.fixed-top = t('.title')
- if flash.notice.present? 
  .container.pt-3
    .alert.alert-success = flash.notice
table.table.table-striped
  thead
    tr.bg-light
      th = t('.date')
      th = t('.staple_food')
  tbody
    - @menus.each do |menu|
      tr
        td = l menu.date, format: :short
        td = menu.cooking_repertoire.name

app/views/menus/new.slim
h4.py-3.text-center.bg-primary.text-light.fixed-top = t('.title')
.container.pt-3
  - if flash.notice.present? 
    .alert.alert-danger = flash.notice
  = form_with model: @menu, local: true do |form|
    .form-group
      = form.label :date
      = form.date_field :date, value: Date.today, class: 'form-control'
    .form-group
      = form.label :period
      = form.select :period, options_for_select(periods), {}, class: 'form-control'
    .form-group
      = form.label :not_duplicate_day
      = form.select :not_duplicate_day, options_for_select(not_duplicate_days), {}, class: 'form-control'
    .form-group
      p = t('.menus_are_created_from_repertoires_that_include_checked_tags')
      - @tags.each do |tag|
        label.form-control.mb-3.font-size-lg
          - if MenuCandidateTag.where(tag_id: tag).exists? || MenuCandidateTag.all.empty?
            = check_box_tag 'tag_candidates[tags][]', tag.id, checked = true, id: tag.id, class: 'mr-2'
          - else
            = check_box_tag 'tag_candidates[tags][]', tag.id, checked = false, id: tag.id, class: 'mr-2'
          = label_tag :tag, tag.name, for: tag.id
    .form-group
      = form.submit class: 'btn btn-lg btn-warning text-light form-control mb-3'

app/views/tags/index.slim
h4.py-3.bg-warning.text-light.text-center.fixed-top
  = t('.title')
.container
  - if flash.notice.present? 
    .alert.alert-success.my-2.text-break = flash.notice
- @tags.each do |tag|
  .container
    h5.border-bottom.py-3 = tag.name
  .container.d-flex.flex-wrap
    - if tag.cooking_repertoires.present?
      - tag.cooking_repertoires.each do |cooking_repertoire|
        - unless cooking_repertoire.tags.exists?(name: t('activerecord.attributes.tag.delete'))
          .col-6.col-md-3.p-2
            .card
              .card-body.w-100.h-100.position-absolute.overflow-auto
                = link_to cooking_repertoire.name, cooking_repertoire_path(cooking_repertoire.id), class: 'stretched-link'
    - else
      = t('.no_repertoire_name')